force-app/main/default/objects/KReservation__c/KReservation__c.object-meta.xml
<CustomObject>
    <label>KReservation</label>
    <nameField>
        <label>KReservation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KReservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/KReservation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>KReservations</relationshipLabel>
    <relationshipName>KReservations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/KReservation__c/fields/KRoom__c.field-meta.xml
<CustomField>
    <fullName>KRoom__c</fullName>
    <label>KRoom</label>
    <referenceTo>KRoom__c</referenceTo>
    <relationshipLabel>KReservations</relationshipLabel>
    <relationshipName>KReservations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/KRoom__c/KRoom__c.object-meta.xml
<CustomObject>
    <label>KRoom</label>
    <nameField>
        <displayFormat>R-{000}</displayFormat>
        <label>RoomNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KRooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/KDEMOSOQL.cls
public with sharing class KDEMOSOQL {

    public static void CreateReservation()
    {
        KReservation__c res= new KReservation__c ();
        res.Contact__c='0035j00000LsP9DAAV';
        res.KRoom__c='a075j000007wMV5AAM';
        res.Name='Reservaation created form Apex code';
        res.StartDate__c =date.parse('3/1/2023');
        res.EndDate__c =date.parse('3/15/2023');
        
        insert res;
    
    }



}