force-app/main/default/objects/KHotel__c/KHotel__c.object-meta.xml
<CustomObject>
    <label>KHotel</label>
    <nameField>
        <label>HotelName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KHotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KHotel__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>State__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Hubli</fullName>
            </value>
            <value>
                <fullName>Dharwad</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Coimbatore</fullName>
            </value>
            <value>
                <fullName>Madurai</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Nasik</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Nagpur</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/KBatchApexDemo.cls
public class KBatchApexDemo implements Database.Batchable<sObject> {

    public Database.QueryLocator  start(Database.BatchableContext bc) {
       
        string query='Select Id,Name, City__c  from KHotel__c';

        return Database.getQueryLocator(query);
               
    }
    public void execute(Database.BatchableContext bc, List<KHotel__c> hotels){

        for(KHotel__c ht:hotels)
        {
            ht.Name='IN ' +ht.Name;
            
        }
       try {
        
        update hotels;
       } 
       catch (Exception ex) {
         System.debug('Exception has occured in the code of batch job'+ex.getMessage());
        
       }

    }
    public void finish(Database.BatchableContext bc){
        // execute any post-processing operations
    }
}