force-app/main/default/objects/KHotel__c/KHotel__c.object-meta.xml
<CustomObject>
    <label>KHotel</label>
    <nameField>
        <label>HotelName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KHotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KRoom__c/KRoom__c.object-meta.xml
<CustomObject>
    <label>KRoom</label>
    <nameField>
        <displayFormat>R-{000}</displayFormat>
        <label>RoomNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KRooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/KRoom__c/fields/KHotel__c.field-meta.xml
<CustomField>
    <fullName>KHotel__c</fullName>
    <label>KHotel</label>
    <referenceTo>KHotel__c</referenceTo>
    <relationshipLabel>KRooms</relationshipLabel>
    <relationshipName>KRooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/KRoom__c/fields/Occupancy__c.field-meta.xml
<CustomField>
    <fullName>Occupancy__c</fullName>
    <label>Occupancy</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Double</fullName>
            </value>
            <value>
                <fullName>Executive</fullName>
            </value>
            <value>
                <fullName>Deluxe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/KHotelTriggerHandler.cls
public with sharing class KHotelTriggerHandler {

          public static void HotelBeforeOperation(List<KHotel__c> hotels)
       {
          for(KHotel__c h: hotels)
            {
                List<KHotel__c> hotlesList= [Select Id,Name from KHotel__c Where Name=:h.Name];
                   if(hotlesList.size()>0)
                   {
                       h.addError('Testing again Hotel with Name already Exists Thank you try creating with New Name');
                   }
                   else
                   {
                      h.Name= h.Name + ' Before INDIA';
                   }                         
               }
       }
       
       public static void HotelAfterOperation(List<KHotel__c> hotels)
       {
           List<KRoom__c> roomsList = new List<KRoom__c>();
           for(KHotel__c h: hotels)
               {
                 KRoom__c r= new KRoom__c();
                  r.KHotel__c= h.Id;
                  r.Occupancy__c='Single';            
                  roomsList.add(r);
                }
                  if(roomsList.size()>0)
                   {
                       insert roomsList;
                   }
        }
       

       
       
   }